### ISSUE TITLE
Vino and ONTAP 9.15.1changes not captured in this document. We need to update or archive this document. 

### ISSUE THREAD

**Issue by randallk72** [NetAppDocs/ontap-metrocluster#446] opened 2024-12-13 15:15 UTC
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html

### Page title

Upgrade controllers in a four-node MetroCluster IP configuration using switchover and switchback with

### Summary

This document was followed to do a Vino upgrade and a few critical steps were missed.  See case https://smartsolvecm.netapp.com/ui/#/case/2010136567 and CPE https://jira.ngage.netapp.com/browse/CPE-8111. Can we update this document or archive it?  Example:    The value for HA-partner-IP-address must be set to 0 (zero) on systems introduced in ONTAP 9.15.1 or later because they have separate ports for DR and HA.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment] 2024-12-15 18:14
Closing this as the issue is being tracked internally in ONTAPDOC-2598.

**Closed by netapp-aoife** 2024-12-15 18:14 UTC
