### ISSUE TITLE
Title in Table

### ISSUE THREAD

**Issue by frechna** [NetAppDocs/ontap-metrocluster#294] opened 2023-05-24 08:32 UTC
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_isls.html

### Page title

Considerations for ISLs

### Summary

Hi Team,

for a better understanding of the ISL Table it might be better to write "maximum Number of ISLs" insteed of "Number of ISLs". It was not clear to me if this is the minimum number of required ISLs or a recommendation or the maximum per Switch. But technicially it looks like the maximum number of ISLs per Switch compared to the ISL Section in HWU.

BR Denny

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment] 2023-05-24 08:49
Hello. Thank you for this feedback. We'll let you know when this has been addressed in the documentation.

**Comment by netapp-aoife** [comment] 2024-03-29 10:44
Hi @frechna thanks again for this feedback. The issue is now addressed in the documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-requirements-isls.html#supported-number-of-isls-and-breakout-cables

**Closed by netapp-aoife** 2024-03-29 10:44 UTC
Labels: documentation
