### ISSUE TITLE
German version of "state" is not "Bundesland" it is "Status" or "Zustand" 

### ISSUE THREAD

**Issue by TomHolzknechtNetApp** [NetAppDocs/ontap-metrocluster#248] opened 2022-12-15 07:45 UTC
Page: [MetroCluster Datensicherung und Disaster Recovery verstehen](https://docs.netapp.com/de-de/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html)

![image](https://user-images.githubusercontent.com/111429179/207801866-36d09841-cf3d-464b-9b42-cdde81443909.png)

**Comment by netapp-gudugunti** [comment] 2023-03-14 08:08
Thanks! for reporting the issue, @TomHolzknechtNetApp.
The issue is fixed with "Status" as the translated term.

**Closed by netapp-gudugunti** 2023-03-14 08:08 UTC
Labels: documentation
